### ISSUE TITLE
Failt to run with parameters.txt

### ISSUE THREAD

**Issue by daqiangpan** [adelabriere/SLAW#1]
I can finish the first run to generate the parameters.txt, but when I rerun the command with parameters.txt, it failt at the very beginning. Can anybody help me? I am new to this world :)

docker run -v /Users/Downloads/Test_input:/input -v /Users/Downloads/Test_output:/output adelabriere/slaw:latest
2021-01-08|22:08:00|INFO: Total memory available: 1197 and 2 cores. The workflow will use 1257 Mb by core on 0.0 cores.
2021-01-08|22:08:00|INFO: Guessing polarity from file:DDA1.mzML
2021-01-08|22:08:02|INFO: Polarity detected: positive
2021-01-08|22:08:04|INFO: STEP: initialisation TOTAL_TIME:3.88s LAST_STEP:3.88s
2021-01-08|22:08:04|INFO: Empty directory detected, performing initial guess of SLAW parameters.
2021-01-08|22:08:04|INFO: Parameters file generated please check the parameters values/ranges and toggle optimization if needed.
docker run -v /Users/Downloads/Test_input:/input -v /Users/Downloads/Test_output:/output adelabriere/slaw:latest
2021-01-08|22:08:15|INFO: Total memory available: 1196 and 2 cores. The workflow will use 1257 Mb by core on 0.0 cores.
2021-01-08|22:08:15|INFO: Guessing polarity from file:DDA1.mzML
2021-01-08|22:08:17|INFO: Polarity detected: positive
2021-01-08|22:08:19|INFO: STEP: initialisation TOTAL_TIME:3.82s LAST_STEP:3.82s
2021-01-08|22:08:21|INFO: 4 peakpicking added
Traceback (most recent call last):
  File "wrapper_docker.py", line 217, in <module>
    exp.run_openms(min_peakwidth, max_peakwidth, peak_width_fac, sn, ppm, min_int, max_outlier, min_scan, quant,log = LOG)
  File "/pylcmsprocessing/model/experiment.py", line 496, in run_openms
    runner.run(clis, silent=silent, log = log, timeout = cr.CONSTANT["PEAKPICKING_TIMOUT"])
  File "/pylcmsprocessing/model/helper/parallel_runner.py", line 60, in run
    with mp.Pool(min(self.max_jobs,len(command_lines))) as executor:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by adelabriere** [comment]
Hi,

The problem seems to be that your docker desktop on windows is not allocated enough memory, 2 cores and 1196 Mo of RAM is not enough.
You can increase the memory allocated in as described in docker documentation:
[Docker doc](https://docs.docker.com/docker-for-windows/)
and going into the Resources🔗 of the Docker desktop settings.
To have good results you should allocate at least 4 cores and at least 1500 Mo times the number of cores. The more the better.
I ll create a page with an explanation about this process this week, and a more meaningful error message for this specific case.

For more detail :
To get the number of Cores used, SLAW take the minimum between (Detected memory (Mb)/1250) and the allocated number of cores. Here because there is only 1196Mb detected this number is 0.

Best,
Alexis Delabriere

**Comment by daqiangpan** [comment]
Thank you very much! It worked!
