### ISSUE TITLE
Bug: 0.0 processors

### ISSUE THREAD

**Issue by che25** [adelabriere/SLAW#7]
Hi Alexis,

I've got a problem with the demo data. It seems that the number of processors is zero. Below is the log from the console. It was run on OSX.

Before, I successfully ran the command to generate the parameter file.

Best 

Christian

META-005:Slaw cedlich$ docker run --rm -v ~/Slaw/Input/mzML:/input -v ~/Slaw/Output:/output adelabriere/slaw:latest
2021-08-23|08:52:56|INFO: Total memory available: 1158 and 2 cores. The workflow will use 1257 Mb by core on 0.0 cores.
2021-08-23|08:52:56|INFO: Guessing polarity from file:DDA1.mzML
2021-08-23|08:52:57|INFO: Polarity detected: positive
2021-08-23|08:52:58|INFO: STEP: initialisation TOTAL_TIME:2.00s LAST_STEP:2.00s
2021-08-23|08:52:59|INFO: 4 peakpicking added
Traceback (most recent call last):
  File "wrapper_docker.py", line 217, in <module>
    exp.run_openms(min_peakwidth, max_peakwidth, peak_width_fac, sn, ppm, min_int, max_outlier, min_scan, quant,log = LOG)
  File "/pylcmsprocessing/model/experiment.py", line 496, in run_openms
    runner.run(clis, silent=silent, log = log, timeout = cr.CONSTANT["PEAKPICKING_TIMOUT"])
  File "/pylcmsprocessing/model/helper/parallel_runner.py", line 60, in run
    with mp.Pool(min(self.max_jobs,len(command_lines))) as executor:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by adelabriere** [comment]
Hi @che25 , thanks for reporting the issue. The problem is that you have very little memory for your docker installation 1158 Mo is clearly lower than what I had in mind you could maybe try to increase it ([link](https://docs.docker.com/desktop/mac/)). As MZmine ADAP require a lot of memory, the minimum used by SLAW for a peak-picking is 1250 Mb. 

You can in all cases bypass the memory and number of cores precomputed by SLAW by setting the MEMORY and NCORES environment variables: 'docker run -e MEMORY=1150 -e NCORES=2 ....' in your case.

 Your memory will however probably not be sufficient for any decent sized acquisition, and the preferred solution should be to increase it.

I m currently updating SLAW so the error message in this case is less confusing, and it try to run SLAW on a single core in every cases.

Alexis

**Comment by che25** [comment]
Hi Alexis,

Thank you for your quick response.

I tried with passing the environmental variables but it crashed again:

META-005:Slaw cedlich$ docker run -e MEMORY=1150 -e NCORES=2 --rm -v ~/Slaw/Input/mzML:/input -v ~/Slaw/Output:/output adelabriere/slaw:latest
2021-08-23|09:24:02|INFO: Total memory available: 1154 and 2 cores. The workflow will use 1150 Mb by core on 1 cores.
2021-08-23|09:24:02|INFO: Guessing polarity from file:DDA1.mzML
2021-08-23|09:24:03|INFO: Polarity detected: positive
2021-08-23|09:24:04|INFO: STEP: initialisation TOTAL_TIME:2.19s LAST_STEP:2.19s
2021-08-23|09:24:05|INFO: 0 peakpicking added
Traceback (most recent call last):
  File "wrapper_docker.py", line 217, in <module>
    exp.run_openms(min_peakwidth, max_peakwidth, peak_width_fac, sn, ppm, min_int, max_outlier, min_scan, quant,log = LOG)
  File "/pylcmsprocessing/model/experiment.py", line 496, in run_openms
    runner.run(clis, silent=silent, log = log, timeout = cr.CONSTANT["PEAKPICKING_TIMOUT"])
  File "/pylcmsprocessing/model/helper/parallel_runner.py", line 60, in run
    with mp.Pool(min(self.max_jobs,len(command_lines))) as executor:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

The same with NCORES=1. I will try on the cluster but it would be great to have a toy example to play around with on my local computer.

Best,

Christian

**Comment by adelabriere** [comment]
Mmm yes sorry, I just realized there is a logic flaw such that if the estimated number of cores is too low it will bypass the command line. I am fixing it and I will upload a 'slaw:dev' Docker before the end of the day. I ll tag you here once it is done.

**Comment by adelabriere** [comment]
I pushed a dev version where I corrected the incriminated bug, normally the NCORES and MEMORY will now by accounted for properly, you can download it:
`docker pull adelabriere/slaw:dev`
@che25

**Comment by che25** [comment]
Hi Alexis,

Thanks again for your quick response.

I am sorry that I have no good news: I pulled the :dev docker image but the error is the same as before.

Best,

Christian


META-005:Slaw cedlich$ docker run -e MEMORY=1150 -e NCORES=2 --rm -v ~/Slaw/Input/mzML:/input -v ~/Slaw/Output:/output adelabriere/slaw:dev
2021-08-24|07:11:57|INFO: Total memory available: 1189 and 2 cores. The workflow will use 1150 Mb by core on 2 cores.
2021-08-24|07:11:57|INFO: Guessing polarity from file:DDA1.mzML
2021-08-24|07:11:58|INFO: Polarity detected: positive
2021-08-24|07:11:58|INFO: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2021-08-24|07:11:59|INFO: STEP: initialisation TOTAL_TIME:2.05s LAST_STEP:2.05s
2021-08-24|07:11:59|INFO: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2021-08-24|07:12:00|INFO: 0 peakpicking added
Traceback (most recent call last):
  File "wrapper_docker.py", line 211, in <module>
    exp.run_openms(min_peakwidth, max_peakwidth, peak_width_fac, sn, ppm, min_int, max_outlier, min_scan, quant,log = LOG)
  File "/pylcmsprocessing/model/experiment.py", line 489, in run_openms
    runner.run(clis, silent=silent, log = log, timeout = cr.CONSTANT["PEAKPICKING_TIMOUT"])
  File "/pylcmsprocessing/model/helper/parallel_runner.py", line 62, in run
    with mp.Pool(min(self.max_jobs,len(command_lines))) as executor:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by adelabriere** [comment]
Hi Christian , I am sorry to hear that. It is then an issue that I never encountered before as it is not related to the memory or the number of processors anymore.  The thing which surprises me in your output is this line:

> 2021-08-24|07:12:00|INFO: 0 peakpicking added

This was never the case in my setups (HPC CentOS, windows 10, and Ubuntu desktop) especially since you have 

> 2021-08-24|07:11:57|INFO: Guessing polarity from file:DDA1.mzML

Which indicates that the folder is mounted correctly. I still think however that there is a problem with the input or output folder:

- Is the output folder empty ? If not delete everything except the `parameters.txt` file and retry it. It is possible that an artifact from the first failed processing remains in the folder.
-  Can you check that the inputs mzML are all in the folder, there should be 6 ?

If none of that work I will try to find a Mac to reproduce the issues as I never encountered it on Linux or windows.

**Comment by che25** [comment]
H Alexis,

Success finally!

Deleting everything except the parameter file did it, even without specifying memory.

Thank you again. I will start playing around with it.

Best

Christian
