### ISSUE TITLE
dev version does not create parameter file

### ISSUE THREAD

**Issue by che25** [adelabriere/SLAW#8]
Hi Alexis, 

sorry to bother you again.

The dev version which is able to run with the parameter file in the output directory cannot create the parameter file from scratch. 

META-005:Slaw cedlich$ rm -r Output
META-005:Slaw cedlich$ mkdir Output
META-005:Slaw cedlich$ docker run -e MEMORY=1100 -e NCORES=2 --rm -v ~/Slaw/Input/mzML:/input -v ~/Slaw/Output:/output adelabriere/slaw:dev

2021-08-31|06:40:46|INFO: Total memory available: 1498 and 2 cores. The workflow will use 1100 Mb by core on 2 cores.
2021-08-31|06:40:46|INFO: Guessing polarity from file:DDA1.mzML
2021-08-31|06:40:47|INFO: Polarity detected: positive
2021-08-31|06:40:47|INFO: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2021-08-31|06:40:48|INFO: STEP: initialisation TOTAL_TIME:2.24s LAST_STEP:2.24s
Traceback (most recent call last):
  File "wrapper_docker.py", line 134, in <module>
    vui.generate_yaml_files()
  File "/pylcmsprocessing/model/helper/UI.py", line 59, in generate_yaml_files
    self.initialize_yaml_polarity(self.path_yaml,self.polarity)
  File "/pylcmsprocessing/model/helper/UI.py", line 36, in initialize_yaml_polarity
    with open(path_yaml, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'positive'

Best

Christian

**Comment by adelabriere** [comment]
Hi @che25. Sadly I pushed a version with some work in progress, notably in the parameter generations. I have a clean version in progress but it won t be ready before the end of the week. I ll push it when it is ready on the main branch and tag you here when a clean version is up.

**Comment by che25** [comment]
Hi Alexis,

I would like to carry on testing slaw with singularity on the server. Try out parameter optimisation.

Is the new version coming out soon?  

Alternatively, if you could direct me to the code version on GitHub that corresponds to slaw:latest (where I am assuming the parameter file problems do not arise), I could build my own docker version from that. As it is, the version on GitHub is also broken.

Best,

Christian
